### ISSUE TITLE
Specular color

### ISSUE THREAD

**Issue by petermcevoy** [vidarn/ThunderLoom#6]
Allow changing the color of the specular reflections.

**Comment by sharktacos** [comment]
@petermcevoy To clarify this issue, since the specular color would often be the same as the diffuse color (really in almost every case that one would want to have spec color with only a few possible exceptions), it would be important to have a slider that would control the amount that the spec color is _tinted_ by the diffuse color. There would therefore need to be 3 new parameters for each yarn type:

1) specular color (this issue #6)
2) spec amount (this is the same as issue #2 "Mult helper sliders for colors")
**3) "tint spec" amount slider**
